var classes = [
    {
        "name": "BASE\\Database\\MySQL",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 10,
        "ccnMethodMax": 10,
        "externals": [
            "RuntimeException",
            "mysqli",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 59,
        "vocabulary": 19,
        "volume": 250.63,
        "difficulty": 9.23,
        "effort": 2313.49,
        "level": 0.11,
        "bugs": 0.08,
        "time": 129,
        "intelligentContent": 27.15,
        "number_operators": 19,
        "number_operands": 40,
        "number_operators_unique": 6,
        "number_operands_unique": 13,
        "cloc": 22,
        "loc": 48,
        "lloc": 26,
        "mi": 94.33,
        "mIwoC": 50.99,
        "commentWeight": 43.34,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "BASE\\Database\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "BASE\\MVC\\Controller",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "BASE\\Config",
            "fullClassName"
        ],
        "parents": [],
        "lcom": 1,
        "length": 53,
        "vocabulary": 23,
        "volume": 239.75,
        "difficulty": 6.53,
        "effort": 1565.42,
        "level": 0.15,
        "bugs": 0.08,
        "time": 87,
        "intelligentContent": 36.72,
        "number_operators": 16,
        "number_operands": 37,
        "number_operators_unique": 6,
        "number_operands_unique": 17,
        "cloc": 21,
        "loc": 41,
        "lloc": 20,
        "mi": 99.17,
        "mIwoC": 54.42,
        "commentWeight": 44.76,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 5.33,
        "package": "       BASE\\    MVC\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "BASE\\MVC\\TemplateEngines\\Smarty\\ParentController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadPlugins",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "displayTemplates",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "BASE\\MVC\\TemplateEngines\\ParentController",
            "Smarty",
            "BASE\\Config",
            "BASE\\Config",
            "BASE\\Config",
            "BASE\\Config",
            "BASE\\MVC\\TemplateEngines\\Smarty\\Plugins\\Link",
            "RuntimeException",
            "BASE\\Config"
        ],
        "parents": [],
        "lcom": 1,
        "length": 94,
        "vocabulary": 28,
        "volume": 451.89,
        "difficulty": 6.96,
        "effort": 3143.59,
        "level": 0.14,
        "bugs": 0.15,
        "time": 175,
        "intelligentContent": 64.96,
        "number_operators": 30,
        "number_operands": 64,
        "number_operators_unique": 5,
        "number_operands_unique": 23,
        "cloc": 55,
        "loc": 102,
        "lloc": 47,
        "mi": 89.64,
        "mIwoC": 44.26,
        "commentWeight": 45.38,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.05,
        "relativeSystemComplexity": 169.05,
        "totalStructuralComplexity": 676,
        "totalDataComplexity": 0.21,
        "totalSystemComplexity": 676.21,
        "package": "   BASE\\MVC\\",
        "pageRank": 0.11,
        "afferentCoupling": 2,
        "efferentCoupling": 5,
        "instability": 0.71,
        "violations": {}
    },
    {
        "name": "BASE\\MVC\\TemplateEngines\\Smarty\\Plugins\\Link",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "BASE\\MVC\\Links",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 24,
        "vocabulary": 10,
        "volume": 79.73,
        "difficulty": 8.5,
        "effort": 677.67,
        "level": 0.12,
        "bugs": 0.03,
        "time": 38,
        "intelligentContent": 9.38,
        "number_operators": 7,
        "number_operands": 17,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 27,
        "loc": 43,
        "lloc": 16,
        "mi": 106.96,
        "mIwoC": 59.88,
        "commentWeight": 47.08,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "       BASE\\MVC\\TemplateEngines\\Smarty\\Plugins\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "BASE\\MVC\\Local",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "BASE\\MVC\\Uri",
            "BASE\\Config",
            "BASE\\Config"
        ],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 8,
        "volume": 63,
        "difficulty": 6,
        "effort": 378,
        "level": 0.17,
        "bugs": 0.02,
        "time": 21,
        "intelligentContent": 10.5,
        "number_operators": 9,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 4,
        "cloc": 12,
        "loc": 33,
        "lloc": 21,
        "mi": 98.09,
        "mIwoC": 57.89,
        "commentWeight": 40.21,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 5,
        "package": "       BASE\\MVC\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "BASE\\MVC\\Uri",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getUri",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLocalCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "BASE\\Helper\\RegExp"
        ],
        "parents": [],
        "lcom": 3,
        "length": 34,
        "vocabulary": 13,
        "volume": 125.81,
        "difficulty": 6.56,
        "effort": 825.66,
        "level": 0.15,
        "bugs": 0.04,
        "time": 46,
        "intelligentContent": 19.17,
        "number_operators": 13,
        "number_operands": 21,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 22,
        "loc": 49,
        "lloc": 27,
        "mi": 96.61,
        "mIwoC": 53.54,
        "commentWeight": 43.07,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 16,
        "package": "       BASE\\MVC\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "BASE\\MVC\\Routes",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getControllerByUri",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoutes",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 22,
        "ccnMethodMax": 16,
        "externals": [
            "BASE\\Helper\\RegExp",
            "RuntimeException",
            "BASE\\Config",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "BASE\\Helper\\RegExp",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 177,
        "vocabulary": 48,
        "volume": 988.54,
        "difficulty": 16.05,
        "effort": 15868.64,
        "level": 0.06,
        "bugs": 0.33,
        "time": 882,
        "intelligentContent": 61.58,
        "number_operators": 55,
        "number_operands": 122,
        "number_operators_unique": 10,
        "number_operands_unique": 38,
        "cloc": 48,
        "loc": 135,
        "lloc": 87,
        "mi": 73.66,
        "mIwoC": 33.76,
        "commentWeight": 39.89,
        "kanDefect": 1.82,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.23,
        "relativeSystemComplexity": 26.23,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 6.17,
        "totalSystemComplexity": 131.17,
        "package": "       BASE\\MVC\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "BASE\\MVC\\Links",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "setRoutes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUri",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 12,
        "ccnMethodMax": 10,
        "externals": [
            "InvalidArgumentException",
            "RuntimeException",
            "BASE\\Helper\\RegExp",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 95,
        "vocabulary": 31,
        "volume": 470.65,
        "difficulty": 9.04,
        "effort": 4255.45,
        "level": 0.11,
        "bugs": 0.16,
        "time": 236,
        "intelligentContent": 52.05,
        "number_operators": 33,
        "number_operands": 62,
        "number_operators_unique": 7,
        "number_operands_unique": 24,
        "cloc": 25,
        "loc": 77,
        "lloc": 52,
        "mi": 80.86,
        "mIwoC": 42.24,
        "commentWeight": 38.62,
        "kanDefect": 1.4,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.25,
        "relativeSystemComplexity": 3.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 6.5,
        "package": "       BASE\\MVC\\",
        "pageRank": 0.12,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "BASE\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadXml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHostParameter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAppDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAppDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplateEngine",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 11,
        "ccnMethodMax": 5,
        "externals": [
            "stdClass",
            "stdClass",
            "RuntimeException",
            "stdClass",
            "RuntimeException",
            "InvalidArgumentException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 6,
        "length": 67,
        "vocabulary": 27,
        "volume": 318.58,
        "difficulty": 5.29,
        "effort": 1683.91,
        "level": 0.19,
        "bugs": 0.11,
        "time": 94,
        "intelligentContent": 60.27,
        "number_operators": 30,
        "number_operands": 37,
        "number_operators_unique": 6,
        "number_operands_unique": 21,
        "cloc": 57,
        "loc": 122,
        "lloc": 65,
        "mi": 85.04,
        "mIwoC": 41.45,
        "commentWeight": 43.59,
        "kanDefect": 0.87,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.78,
        "relativeSystemComplexity": 5.78,
        "totalStructuralComplexity": 24,
        "totalDataComplexity": 10.67,
        "totalSystemComplexity": 34.67,
        "package": "       BASE\\",
        "pageRank": 0.23,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "BASE\\MVC",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "BASE\\Config",
            "BASE\\MVC\\Uri",
            "BASE\\MVC\\Local",
            "BASE\\MVC\\Routes",
            "BASE\\MVC\\Links",
            "BASE\\MVC\\Controller"
        ],
        "parents": [],
        "lcom": 1,
        "length": 34,
        "vocabulary": 14,
        "volume": 129.45,
        "difficulty": 4.4,
        "effort": 569.58,
        "level": 0.23,
        "bugs": 0.04,
        "time": 32,
        "intelligentContent": 29.42,
        "number_operators": 12,
        "number_operands": 22,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 12,
        "loc": 38,
        "lloc": 26,
        "mi": 92.18,
        "mIwoC": 53.94,
        "commentWeight": 38.23,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 49.38,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.38,
        "totalSystemComplexity": 49.38,
        "package": "       BASE\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "BASE\\Helper\\RegExp",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "getLocalCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRegExp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.5,
        "effort": 3.17,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 12.68,
        "number_operators": 2,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 19,
        "loc": 31,
        "lloc": 12,
        "mi": 117.54,
        "mIwoC": 70.71,
        "commentWeight": 46.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "       BASE\\    Helper\\",
        "pageRank": 0.18,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "BASE\\Controller\\Stores",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "overview",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "details",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "BASE\\MVC\\TemplateEngines\\Smarty\\ParentController"
        ],
        "parents": [
            "BASE\\MVC\\TemplateEngines\\Smarty\\ParentController"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 0,
        "effort": 0,
        "level": 1.11,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 66.32,
        "mIwoC": 66.32,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 4.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 8.33,
        "package": "BASE\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "BASE\\Controller\\Website",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "homepage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "BASE\\MVC\\Links"
        ],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0.5,
        "effort": 6.97,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 27.86,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 71.04,
        "mIwoC": 71.04,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "BASE\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "BASE\\Controller\\About",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "overview",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "history",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "BASE\\MVC\\TemplateEngines\\Smarty\\ParentController"
        ],
        "parents": [
            "BASE\\MVC\\TemplateEngines\\Smarty\\ParentController"
        ],
        "lcom": 2,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 71.59,
        "mIwoC": 71.59,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 2,
        "package": "BASE\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]